### ISSUE TITLE
[EPIC] The great refactor -- tracking huge changes across the code base

### ISSUE THREAD

**Issue by Skarlso** [photoprism/photoprism#49]
Hi! 

Great project! The Go part needs a bit of polishing I begun doing.

Here are some notes that I started hammering on:

- [ ] Remove the convoluted way configuration is created and replace it with proper yaml marshalling (#50)
- [ ] Add documentation to exported values (#50)
- [ ] Restrict exported fields if they aren't really used, there is no need to export them ( there are lot of exported fields which don't really need to be exported. ). (#50)
- [ ] See if it's really necessary to share all the structures with a pointer making them escape to heap. If they aren't modified or required to be modified it's enough to pass them by value and making them stay on stack.
- [ ] Make the database injectable ( this is quite likely the biggest of changes and probably needs to be tracked in a separate ticket. ).
- [ ] Extract services and put them into their own package so other packages can access them if they are needed.
- [ ] Write some more tests
- [ ] Reduce complexity by extracting small behaviour and eventually refactor them to use a different approach. Once smaller components are extracted it will be much easier to see what can be thrown out or made simpler.
- [ ] Remove `.` imports
- [ ] Indexing can take a lot of time for many pictures and Tensorflow adds to that. This should be extracted into a semaphore controlled parallel process. Since they aren't connected it should be possible to make it parallel rather than concurrent

That's all for now as a quick glance. :) I'll extract stuff in here into different tickets to track them via different PRs if you don't mind of course.

Also, I started into the first three points together since they would cause a lot of code conflicts if done separately.

**Comment by lastzero** [comment]
Thank you! 👍 

I do (and encourage others to do) most refactoring in an opportunistic way, when there is a specific problem or I'm working on the code anyways (so that there is no need for extra "refactoring" tickets or epics). I expect this to be difficult when working with a distributed team and pull requests. Let's experiment and start as you suggest. Your help is much appreciated.

**Comment by Skarlso** [comment]
Cheers! Oh yeah, probably going to end up causing some trouble here and there. But nothing too much I think. :) 👍

**Comment by lastzero** [comment]
Added a [page about code quality](https://github.com/photoprism/photoprism/wiki/Code-Quality) in our Developer Guide.
