### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#58]
**As a developer, I want increased unit test coverage to have a smoother development experience and greater confidence.**

Acceptance Criteria: 
- [x] Public code coverage / code quality report
- [ ] Each package must have tests covering 90% of the code
- [x] All tests should run in less than 10 minutes, ideally 5 minutes or less (conversion of RAW images can take some time...)

**Comment by lastzero** [comment]
Not reached our % goal, but we take care of it day by day. Closing this.
